### ISSUE TITLE
salt-master can't access /usr/share/yomi

### ISSUE THREAD

**Issue by aboe76** [openSUSE/yomi#1]
On suse the salt-master runs as the user `salt` so all files that yomi-formula provides should have the following permissions: `root:salt` so the salt user can read the files.

**Comment by aplanas** [comment]
@aboe76, ouch, I think that I fixed this bug some time ago:

https://build.opensuse.org/package/view_file/openSUSE:Factory/yomi-formula/yomi-formula.spec?expand=1  (lines 137-140)

In my system I have this:

```
localhost:~ # ls -lad /usr/share/yomi/
drwxr-xr-x 5 root salt 4096 Oct 28 09:50 /usr/share/yomi/
localhost:~ # ls -lad /usr/share/yomi/*
-rw-r--r-- 1 root root   53 Oct 22 07:58 /usr/share/yomi/autosign.conf
drwxr-xr-x 2 root root 4096 Oct 28 09:50 /usr/share/yomi/autosign_grains
-rw-r--r-- 1 root root  140 Oct 22 07:58 /usr/share/yomi/eauth.conf
drwxr-xr-x 4 root root 4096 Oct 28 09:50 /usr/share/yomi/kubic
-rw-r--r-- 1 root root  102 Oct 22 07:58 /usr/share/yomi/kubic-file.conf
drwxr-xr-x 2 root root 4096 Oct 28 09:50 /usr/share/yomi/pillar
-rw-r--r-- 1 root root   69 Oct 22 07:58 /usr/share/yomi/pillar.conf
-rw-r--r-- 1 root root  125 Oct 22 07:58 /usr/share/yomi/salt-api.conf
-rw-r--r-- 1 root root   11 Oct 22 07:58 /usr/share/yomi/user-list.txt
```

This makes /usr/share/yomi to root:salt, and the content is root:root, but can be read by other users.

What do you see in your system?

Can you paste the output from `zypper info yomi-formula`?

**Comment by aboe76** [comment]
sudo zypper info yomi-formula
```
Loading repository data...
Reading installed packages...


Information for package yomi-formula:
-------------------------------------
Repository     : Main Repository (OSS)
Name           : yomi-formula
Version        : 0.0.1+git.1570614306.1a4ae0f-1.1
Arch           : noarch
Vendor         : openSUSE
Installed Size : 261.8 KiB
Installed      : Yes
Status         : up-to-date
Source package : yomi-formula-0.0.1+git.1570614306.1a4ae0f-1.1.src
Summary        : Yomi - Yet one more installer
```
and my /usr/share/yomi:
```
ow so you added the `other read` permissions instead of root:salt....then nevermind...

**Comment by aplanas** [comment]
For coherence I changed the `/usr/share/yomi/` directory to root:root, and maintain all the assets in `/usr/share/salt-formula/{states,metadata}` as `root:salt` (as I am not the owner of the directory).

I will spin some VMs and do some testing before closing the bug, if you do not see any other issue.

**Comment by aboe76** [comment]
@aplanas, Not, yet. I'm looking into integrating it with the [saltstack-formulas/salt-formula](https://github.com/saltstack-formulas/salt-formula).

This formula has a different way to manage files in `/etc/salt/master.d/`.

**Comment by aplanas** [comment]
This is cool!

The management of /etc/salt/master.d/ is done in the RPM, so outside from the real formula side. What complications do you see, and how this impact the integration?

I would like to help here.

**Comment by aboe76** [comment]
The only complication I found is that when you use something like `saltstack/salt-formula` the files in `/etc/master.d` will be removed unless the files are prefixed with an underscore `_`.
see: https://github.com/saltstack-formulas/salt-formula/blob/master/salt/master.sls#L30

But the settings could easily be done with some pillar variables because most of the settings are manageable by the `saltstack/salt-formula`.

**Comment by aplanas** [comment]
Very well. I will close this bug then.

If you see something that I can improve in the management of `/etc/master.d`, tell me.

The code in this repo do not touch `/etc/master.d`, only the documentation refers to this directory. The RPM depends on a new package that comes from the version of Salt that we have in openSUSE: `salt-standalone-formulas-configuration`. This is the only place were this directory is touched, to provide a common base where the formulas can be found in openSUSE when SUSE Manager is also installed.

Yomi is completely agnostic of how `/etc/master.d` is managed.

Please, let me know any action that can be done from my side to simplify the integration with `saltstack/salt-formula`, and thanks for the report!

**Comment by aboe76** [comment]
No Yomi can work fine together with the salt-formula, as far as I can see.
