### ISSUE TITLE
Unable to run yomi livecd

### ISSUE THREAD

**Issue by rdouman** [openSUSE/yomi#2]
I'm unable to boot a yomi live CD.  I can reach the boot loader, but nothing after that.  I've attached screenshots of my configuration.  I've experience similar issue with the PXE boot.

![vm_setup](https://user-images.githubusercontent.com/3218965/82448442-03f92980-9aaa-11ea-8a9a-7975b8baf922.PNG)
![yomi_boot](https://user-images.githubusercontent.com/3218965/82448451-052a5680-9aaa-11ea-9b1e-acabbbe1d790.PNG)
![hardware_setup](https://user-images.githubusercontent.com/3218965/82448455-05c2ed00-9aaa-11ea-97a6-e2921938f2ff.PNG)

**Comment by aplanas** [comment]
Confirmed. This seems a bug in Kiwi. I will check

**Comment by davidcassany** [comment]
> Confirmed. This seems a bug in Kiwi. I will check

Yes, this is a known issue for ISOs using the `dmsquash` dracut module. There was a regression that prevented it from being included into the initramfs image.

This was already fixed in upstream (OSInside/kiwi#1431) a couple of weeks ago. This is already part of the next upcoming KIWI release that should be available soon in Tumbleweed.

**Comment by rdouman** [comment]
Thanks, I'll re-test when it's available in Tumbleweed and close accordingly.  Any idea how do I track when it's available in Tumbleweed ?

**Comment by aplanas** [comment]
Looks like that the new KIWI version 9.20.12 is on [Virtualization:Appliances:Staging](https://build.opensuse.org/project/show/Virtualization:Appliances:Staging), from there I guess that the KIWI team will submit to openSUSE:Factory. Once that is accepted from there (after a short time living in the Factory staging projects), a new version of the Yomi image will appear automatically.

**Comment by rdouman** [comment]
I can confirm that the issue has been resolved.  Tested on build 106.2

**Comment by aplanas** [comment]
Shame for me, I just tested the image yesterday. Thanks for confirmation.
