### ISSUE TITLE
"salt node state.apply yomi" fails to create subvolumes

### ISSUE THREAD

**Issue by rdouman** [openSUSE/yomi#4]
I'm trying to install a new kubic node using the yomi installation scripts and I'm experiencing failures when creating the required btrfs subvolumes.

My salt master is a newly installed kubic master node installation:

NAME="openSUSE MicroOS"
VERSION="20200717"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20200717"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20200717"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"

And the worker node is booted from:
openSUSE-Tumbleweed-Yomi.x86_64-1.0.0-livecd-Build108.14.iso

The installation step fails with the following error message:
          ID: subvol_create_/dev/sda2_usr/local
    Function: btrfs.subvolume_created
        Name: @/usr/local
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.8/site-packages/salt/state.py", line 1987, in call
                  ret = self.states[cdata['full']](*cdata['args'], **cdata['kwargs'])
                File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2031, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.8/site-packages/salt/states/btrfs.py", line 106, in wrapper
                  name = kwargs['name']
              KeyError: 'name'
     Started: 12:33:12.563867
    Duration: 1.278 ms
     Changes:   

I've attached the hardware configuration of the node that I'm trying to install

![node_5_salt_installation](https://user-images.githubusercontent.com/3218965/88260961-b1b0d080-ccc5-11ea-809b-2d43fbfac32d.PNG)

[salt_output.txt](https://github.com/openSUSE/yomi/files/4964370/salt_output.txt)

The configuration that I've updated in the yomi pillar's installer.sls
{% set efi = False %}
{% set partition = 'gpt' %}
{% set device_type = 'sd' %}
{% set root_filesystem = 'btrfs' %}
{% set home_filesystem = False %}
{% set snapper = True %}
{% set swap = False %}
{% set mode = 'kubic' %}

**Comment by aplanas** [comment]
Thanks, I will try to reproduce.

**Comment by aplanas** [comment]
Confirmed. There is a bug in the Salt Btrfs module by me. I am fixing it in our openSUSE package and in upstream.

Thanks a lot for the report, I will update here when the fix is available.

**Comment by rdouman** [comment]
Thanks much appreciated :) I'll test and confirm once the fix is available.

**Comment by aplanas** [comment]
The upstream fix is tracked here: https://github.com/saltstack/salt/issues/58012

The opensuse package here: https://github.com/openSUSE/salt/pull/252

**Comment by aplanas** [comment]
The changes in Tumbleweed, Lead and SLE are under revision, but you can test the fix installing salt from https://build.opensuse.org/package/show/systemsmanagement:yomi/salt, or better, using the ISO / PXE boot image from https://build.opensuse.org/package/show/systemsmanagement:yomi/openSUSE-Tumbleweed-Yomi

**Comment by rdouman** [comment]
Tested on Yomi openSUSE-Tumbleweed-Yomi.x86_64-1.0.0-livecd-Build108.22. 
 
The issue mentioned above is resolved:

          ID: subvol_create_/dev/sda2_usr/local
    Function: btrfs.subvolume_created
        Name: @/usr/local
      Result: True
     Comment: Subvolume @/usr/local already present
     Started: 08:22:24.175470
    Duration: 1609.335 ms
     Changes:  

I consider this issue resolved.  I did, however, experience new errors in the installation.  I'll log them accordingly
