### ISSUE TITLE
Snapper install fails

### ISSUE THREAD

**Issue by rdouman** [openSUSE/yomi#5]
I'm trying to install a new kubic node using the yomi installation scripts and I'm experiencing failures when snapper installs.

My salt master is a newly installed kubic master node installation:

NAME="openSUSE MicroOS"
VERSION="20200720"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20200720"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20200720"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"

And the worker node is booted from:
openSUSE-Tumbleweed-Yomi.x86_64-1.0.0-livecd-Build108.22.iso
     
The installation step fails with the following error message:

     ID: snapper_step_two_/dev/sda2
    Function: snapper_install.step_two
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.8/site-packages/salt/state.py", line 1987, in call
                  ret = self.states[cdata['full']](*cdata['args'], **cdata['kwargs'])
                File "/usr/lib/python3.8/site-packages/salt/loader.py", line 2031, in wrapper
                  return f(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/states/snapper_install.py", line 97, in wrapper
                  device = kwargs['device']
              KeyError: 'device'
     Started: 09:47:46.330177
    Duration: 3.079 ms
     Changes:   

The configuration that I've updated in the yomi pillar's installer.sls
{% set efi = False %}
{% set partition = 'gpt' %}
{% set device_type = 'sd' %}
{% set root_filesystem = 'btrfs' %}
{% set home_filesystem = False %}
{% set snapper = True %}
{% set swap = False %}
{% set mode = 'kubic' %}

Please find attched the output from running :  salt 'kubenodetst05' state.apply yomi
[salt_output_28-07-2020.2.txt](https://github.com/openSUSE/yomi/files/4988058/salt_output_28-07-2020.2.txt)

**Comment by aplanas** [comment]
Indeed. This issue and #4 comes from the same upstream change.

Update the formula in the master node from the devel project (https://build.opensuse.org/package/show/systemsmanagement:yomi/yomi-formula).

For reference, the fix was here: https://github.com/openSUSE/yomi/commit/cd0d447023a1fa34fe4491982a586850afcb6bac

**Comment by rdouman** [comment]
Using the devel yomi formula fixed my snapper installation issue.  the installation completed but new the system, however did not boot .  I'll log a new ticket accordingly.
