### ISSUE TITLE
"salt node state.apply yomi" fails to  add custom zypper repos

### ISSUE THREAD

**Issue by rdouman** [openSUSE/yomi#6]
I'm trying to install a new kubic node using the yomi installation scripts.  Our servers sit behind a corporate firewall and I thus require customer zypper repositories to proxy my connection to the outside world.

My salt master is a newly installed kubic master node installation:

NAME="openSUSE MicroOS"
VERSION="20200720"
ID="opensuse-microos"
ID_LIKE="suse opensuse opensuse-tumbleweed"
VERSION_ID="20200720"
PRETTY_NAME="openSUSE MicroOS"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:microos:20200720"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
LOGO="distributor-logo"

And the worker node is booted from:
openSUSE-Tumbleweed-Yomi.x86_64-1.0.0-livecd-Build108.22.iso

The installation step fails with the following error message:
----------
          ID: add_repository_http://registry.domain/repository/Tumbleweed-oss/
    Function: pkgrepo.managed
        Name: repo_oss
      Result: False
     Comment: Failed to configure repo 'repo_oss': Zypper command failure: Unknown problem when adding repository:
              Can't open file '/mnt/etc/zypp/repos.d/repo_oss.repo' for writing.
     Started: 08:22:58.263955
    Duration: 89.853 ms
     Changes:   
----------

I've attached the full output for further reference.
[salt_output_28-07-2020.1.txt](https://github.com/openSUSE/yomi/files/4988100/salt_output_28-07-2020.1.txt)

Adding my installer.sls file
[installer.sls.txt](https://github.com/openSUSE/yomi/files/4988113/installer.sls.txt)

**Comment by aplanas** [comment]
Ahh I see. This seems not to be a bug, but is a consequence of trying to change the read-only subvolume in microos.

For security, Yomi will not wipe the disk, but you can force a clean with https://github.com/openSUSE/yomi#cleaning-the-disks

**Comment by rdouman** [comment]
Wiping the drives as indicated above resolved the issue.  Thanks :)
